############################################################
# +------------------------------------------------------+ #
# |                        HOTBAR                        | #
# +------------------------------------------------------+ #
############################################################
hotbar:
  kit-selector:
    name: "&bKit Selector"
    material: "NETHER_STAR"
    lore: []
    player-commands:
      - "/kits"
    console-commands: []
leaderboards:
  points:
    location: "-36, 8, 9"